

default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['DB_DEVELOPMENT']%>
  
test:
  <<: *default
  database: <%= ENV['DB_TEST']%>

production:
  <<: *default
  database: db/production.sqlite3
