

default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  host: <%= ENV['DEV_DATABASE_HOST']%>
  port: <%= ENV['DEV_DATABASE_PORT']%>
  database: <%= ENV['DEV_DATABASE']%>
  username: <%= ENV['DEV_DATABASE_USER']%>
  password: <%= ENV['DEV_DATABASE_PASSWORD']%>
  
test:
  <<: *development
  database: <%= ENV['DEV_DATABASE_TEST']%>

production:
  <<: *default
  database: <%= ENV['ATABASE_URL']%>
